import type { Metadata } from "next";
import {
  Caveat,
  Fraunces,
  Geist,
  Geist_Mono,
  Inter,
  Open_Sans,
  Poppins,
} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const caveat = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"],
});

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
});

const sans = Open_Sans({
  variable: "--font-sans",
  weight: ["300", "400", "500", "600", "700", "800"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        "font-sans",
        fraunces.variable,
        sans.variable,
        caveat.variable,
      )}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
